"""Ensure rating column is Integer

Revision ID: 1010b0dd6d65
Revises: 0f88709dd408
Create Date: 2024-11-23 14:57:47.229803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1010b0dd6d65'
down_revision: Union[str, None] = '0f88709dd408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
